version: '3'

services:
    loadbalance:
        build: ./nginx
        ports:
            - '80:80'
        networks: 
            - backend
        depends_on: 
            - log
    log:
        build: ./app
        ports: 
            - '101-103'
        networks: 
            - backend
networks:
    backend:


